apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend-app=himanshu369/fastapi-mysql-backend
    argocd-image-updater.argoproj.io/backend-app.pull-secret: pullsecret:argocd/dockerhub-creds
    argocd-image-updater.argoproj.io/backend-app.update-strategy: latest
    argocd-image-updater.argoproj.io/backend-app.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/backend-app.sort: date
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HimanshuVK1/fluid-ai'
    targetRevision: HEAD
    path: backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluid-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
