apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend-app=himanshu369/fastapi-mysql-backend
    argocd-image-updater.argoproj.io/backend-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend-app.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/backend-app.sort: date
    argocd-image-updater.argoproj.io/write-back-method: git:secret:git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    # 2. For Helm:
    # argocd-image-updater.argoproj.io/write-back-target: helmvalues:/values.yaml
    # 3. If omitted, it writes parameters to .argocd-source-backend-app.yaml in the manifests path
spec:
  project: default
  source:
    repoURL: 'https://github.com/HimanshuVK1/fluid-ai'
    # Use an explicit branch name instead of HEAD for Git write-back tracking
    targetRevision: main
    # Use standard forward slashes for Linux Git paths
    path: deploy/services/backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluid-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true