apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-backend.yaml # or whatever your file is named
images:
  - name: himanshu369/fastapi-mysql-backend
    newTag: 919ad55407da3c9549ee3528c467a9ecfe618e58

